exclude orpie from hppa and sparc
According to bug #444494 orpie lists architectures explictly due to this
failure to build from source:

  wrappers.h:13:2: error: #error "Architectures with double-word alignment for doubles are not supported"

This failure happened on both hppa and sparc.

Signed-off-by: Philipp Kern <pkern@debian.org>